### ISSUE TITLE
Необходимо удалить лишнее из манифеста

### ISSUE THREAD

**Issue by zTrap** [iboxpro/android.sdk#1]
Нужно удалить бесполезный тег `<application>` для библиотеки.

На данный момент мерджер манифеста не может нормально смержить манифесты приложения и библиотеки. Падает на момент синка:
```
Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:14:9-36
	is also present at [ibox.pro.sdk.external-release.aar] AndroidManifest.xml:18:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:11:5-60:19 to override.
```

Чинится это (как и сказано в ошибке) добавлением `tools:replace="allowBackup"` в манифест приложения.

**Comment by iboxmpos** [comment]
Исправим в следующем релизе!

**Comment by zTrap** [comment]
И удалить ненужные ресурсы (`app_name`)
